# Generated by Django 5.0.6 on 2024-05-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_research'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='journal',
            new_name='name',
        ),
    ]
