# Generated by Django 5.0.6 on 2024-05-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_research_j_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='paper_type',
            new_name='isJournal',
        ),
        migrations.AddField(
            model_name='research',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
