import "./globals.css";
import Navbar from "@/components/layouts/navbar/Navbar";
import Hero from "@/components/layouts/hero/Hero";
import Footer from "@/components/layouts/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
